### ISSUE TITLE
`make test` failing with ImproperlyConfigured ENGINE

### ISSUE THREAD

**Issue by adborden** [california-civic-data-coalition/django-calaccess-raw-data#1144]
Bails when trying to create the test databases. Since `dat` doesn't have an `ENGINE` value, it uses a dummy value and dies. Remove the `dat` section from settings works fine.

```
$ make test
pep8 calaccess_raw
pyflakes calaccess_raw
coverage run example/manage.py test calaccess_raw
Creating test database for alias 'default'...
E
======================================================================
ERROR: setUpClass (calaccess_raw.tests.CalAccessTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "calaccess_raw/tests.py", line 17, in setUpClass
    super(CalAccessTest, cls).setUpClass()
  File "/home/adborden/.virtualenvs/django-calaccess-raw-data/lib/python2.7/site-packages/django/test/testcases.py", line 946, in setUpClass
    if not connections_support_transactions():
  File "/home/adborden/.virtualenvs/django-calaccess-raw-data/lib/python2.7/site-packages/django/test/testcases.py", line 911, in connections_support_transactions
    for conn in connections.all())
  File "/home/adborden/.virtualenvs/django-calaccess-raw-data/lib/python2.7/site-packages/django/test/testcases.py", line 911, in <genexpr>
    for conn in connections.all())
  File "/home/adborden/.virtualenvs/django-calaccess-raw-data/lib/python2.7/site-packages/django/utils/functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/adborden/.virtualenvs/django-calaccess-raw-data/lib/python2.7/site-packages/django/db/backends/base/features.py", line 216, in supports_transactions
    with self.connection.cursor() as cursor:
  File "/home/adborden/.virtualenvs/django-calaccess-raw-data/lib/python2.7/site-packages/django/db/backends/base/base.py", line 164, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/home/adborden/.virtualenvs/django-calaccess-raw-data/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 21, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

----------------------------------------------------------------------
Ran 0 tests in 0.026s

FAILED (errors=1)
Destroying test database for alias 'default'...
Makefile:31: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by palewire** [comment]
So for these growing pains from our library. I'll work to knock them out for you ASAP.

**Comment by palewire** [comment]
Sorry this took me so long to fix. We're just getting revved up again with @gordonje on board.
