### ISSUE TITLE
Error bootstrapping project

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-raw-data#1161]
Got this running `python example/manage.py downloadcalaccessrawdata` during the **Loading data files** stage

```
Traceback (most recent call last): 0/76 - 00:00:00
  File "example/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/williamsa/.envs/calaccess/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/williamsa/.envs/calaccess/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/williamsa/.envs/calaccess/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/williamsa/.envs/calaccess/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "calaccess_raw/management/commands/downloadcalaccessrawdata.py", line 169, in handle
    self.load()
  File "calaccess_raw/management/commands/downloadcalaccessrawdata.py", line 314, in load
    verbosity=self.verbosity,
  File "/Users/williamsa/.envs/calaccess/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/Users/williamsa/.envs/calaccess/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/williamsa/.envs/calaccess/lib/python2.7/site-packages/django/core/management/base.py", line 548, in handle
    label_output = self.handle_label(label, **options)
  File "calaccess_raw/management/commands/loadcalaccessrawfile.py", line 40, in handle_label
    self.load(label)
  File "calaccess_raw/management/commands/loadcalaccessrawfile.py", line 66, in load
    self.load_postgresql(model, csv_path)
  File "calaccess_raw/management/commands/loadcalaccessrawfile.py", line 162, in load_postgresql
    model._meta.db_table
  File "/Users/williamsa/.envs/calaccess/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/williamsa/.envs/calaccess/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/williamsa/.envs/calaccess/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "CVR_SO_CD" does not exist
```

**Comment by palewire** [comment]
Did you migrate the data tables?

**Comment by aboutaaron** [comment]
Yeah, but I'll blow up the db and try again

**Comment by palewire** [comment]
I worry that I've lost grip on how ``migrate`` works now in 1.9.

**Comment by aboutaaron** [comment]
Nah, it's just me. Forgot to add `makemigrations`. I'll add to the docs

**Comment by gordonje** [comment]
@aboutaaron This makes two of us. @palewire just added some language about managing migrations in the interim. After we starting getting close to version 1.0, I think we'll add the migrations file back to the repo and include 0001_initial.py and any files added as a result of future model changes.

**Comment by palewire** [comment]
I was clearly too dismissive of this issue earlier today. I'll reboot myself from scratch to see if I can recreate it.

**Comment by palewire** [comment]
This is an academic question, but I'm a little confused. Why is it necessary for us to run makemigrations if there is no migration folder on the installed app? 

If you look at the Django documentation's [official tutorial](https://docs.djangoproject.com/en/1.9/intro/tutorial02/#database-setup), it seems to claim you can (as in the past) create tables for migration-less apps with a simple migration.

I wonder if this is a symptom of Django retiring old ``syncdb`` command. [According to the docs](https://docs.djangoproject.com/en/1.9/ref/django-admin/#django-admin-option---run-syncdb) there is now a ``--run-syncdb`` option for migrate that "allows creating tables for apps without migrations."

Out of curiosity, if you delete the calaccess_raw migrations folder and remake your database from scratch, will our table build for you with you run:

```
$ python manage.py migrate --run-syncdb
```

**Comment by palewire** [comment]
AND I HAVE IT. From the removed features list in [the Django 1.9 release notes](https://docs.djangoproject.com/en/1.9/releases/1.9/#features-removed-in-1-9):

```
Automatic syncing of apps without migrations is removed. Migrations are compulsory for all apps unless you pass the --run-syncdb option to migrate.
```

I apologize for all the confusion today and my mistaken ideas. I was simply behind the curve on Django's evolution away from syncdb and optional migrations to the new mandatory migration scheme.

**Comment by gordonje** [comment]
Because `--run-syncdb` is a 1.9 option, I swapped in a `makemigrations calaccess_raw` step instead of `dbsync` so that folks should be able to run `make bootstrap` with either version of Django.

**Comment by gordonje** [comment]
I added a `makemigrations calaccess` step to the bootstrap process. We'll probably want to take that out once we start shipping the migration files with the app.
