### ISSUE TITLE
MigrationError caused by the new DocumentCloud options

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1212]
```python
Traceback (most recent call last):

  File "example/manage.py", line 9, in <module>

    execute_from_command_line(sys.argv)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line

    utility.execute()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute

    output = self.handle(*args, **options)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 143, in handle

    self.write_migration_files(changes)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 171, in write_migration_files

    migration_string = writer.as_string()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/writer.py", line 165, in as_string

    operation_string, operation_imports = OperationWriter(operation).serialize()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/writer.py", line 123, in serialize

    _write(arg_name, arg_value)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/writer.py", line 75, in _write

    arg_string, arg_imports = MigrationWriter.serialize(item)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/writer.py", line 302, in serialize

    item_string, item_imports = cls.serialize(item)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/writer.py", line 376, in serialize

    return cls.serialize_deconstructed(path, args, kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/writer.py", line 267, in serialize_deconstructed

    arg_string, arg_imports = cls.serialize(arg)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/writer.py", line 302, in serialize

    item_string, item_imports = cls.serialize(item)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/writer.py", line 464, in serialize

    "topics/migrations/#migration-serializing" % (value, get_docs_version())

ValueError: Cannot serialize: <calaccess_raw.models.base.DocumentCloud object at 0x7fdc20c9f610>

There are some values Django cannot serialize into migration files.

For more, see https://docs.djangoproject.com/en/1.8/topics/migrations/#migration-serializing
```

**Comment by knowtheory** [comment]
Oh that's interesting.  So the issue here is that Python-DocumentCloud is missing some kind of adapter to serialize out into something Django can stick into a DB?

**Comment by palewire** [comment]
Basically. Though python-documentcloud isn't involved. I invented [a random class](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/base.py#L135-L164) for stuffing in document links with the same name (probably a bad idea). I guess we need some serialization ``deconstruct`` method for that or something.

**Comment by gordonje** [comment]
Adding the deconstructible decorator (as suggested [here](https://docs.djangoproject.com/en/1.8/topics/migrations/#adding-a-deconstruct-method)) to the DocumentCloud class did the trick. This basically just adds a deconstruct method to the class which returns it's path, args and kwargs like so:

```python
('calaccess_raw.models.base.DocumentCloud', (), {'start_page': 3, 'id': 1308004, 'end_page': 7})
```
The serialization error was being raised by the `documentcloud_pages` attribute we've added to some choice fields (e.g., [here](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/campaign.py#L226)), not by any of the other model-level `DOCUMENTCLOUD_PAGES` attributes.

That was one of the things tripping me up. I was operating under the (wrong) assumption that "Django thinks these custom model attributes are database fields, and that's why it's trying to serialize them during migration." This lead me on hunt for how other Django developers handle cases where they want models to include attributes that aren't database columns (there are a few).

But the root of the problem is that our DocumentCloudMixin in fields.py has a deconstruct method, and since DocumentCloud instances are in the documentcloud_pages kwarg, they also need a deconstruct method.

This leaves me wondering, though: Does DocumentCloudMixin need to be serializable / deconstructible? Looks we're borrowing from the second example in [this section](https://docs.djangoproject.com/en/1.8/howto/custom-model-fields/#field-deconstruction) of Django's documentation, but this is showing how to make a custom field class. Django fields definitely need to be serializable / deconstructible in order to migrate the data the fields store. Is this also true for class-based views? 

(Full disclosure: I'm in need of a better understanding of the application of Django's class-based views / mixins).

**Comment by palewire** [comment]
Has this been solved?
