### ISSUE TITLE
IOError running downloadcalaccessrawdata

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-raw-data#226]
```
Cleaning data files
 Cleaning CVR2_SO_CD.TSV
 Cleaning LOBBYIST_EMP_LOBBYIST2_CD.TSV
 Cleaning FILER_ADDRESS_CD.TSV
 Cleaning LOBBYIST_FIRM3_CD.TSV
 Cleaning CVR_REGISTRATION_CD.TSV
  Bad parse of line 30381 (71 headers, 72 values)
CVR_REGISTRATION_CD.TSV had 1 errors
Traceback (most recent call last):
  File "example/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/aaron/.envs/calaccess/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/aaron/.envs/calaccess/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/aaron/.envs/calaccess/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/aaron/.envs/calaccess/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "calaccess_raw/management/commands/downloadcalaccessrawdata.py", line 154, in handle
    self.clean()
  File "calaccess_raw/management/commands/downloadcalaccessrawdata.py", line 276, in clean
    call_command("cleancalaccessrawfile", name)
  File "/home/aaron/.envs/calaccess/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/aaron/.envs/calaccess/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/aaron/.envs/calaccess/local/lib/python2.7/site-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "calaccess_raw/management/commands/cleancalaccessrawfile.py", line 22, in handle_label
    self.clean(label)
  File "calaccess_raw/management/commands/cleancalaccessrawfile.py", line 122, in clean
    self.log_errors(name, log_rows)
  File "calaccess_raw/management/commands/cleancalaccessrawfile.py", line 136, in log_errors
    log_file = open(log_path, 'wb')
IOError: [Errno 2] No such file or directory: '/home/aaron/Code/california-civic-data-coalition/django-calaccess-raw-data/example/data/log/cvr_registration_cd.errors.csv'
```

**Comment by aboutaaron** [comment]
Not sure why there's an error since it's writing a file now reading

**Comment by aboutaaron** [comment]
Code should create `log_dir` if it doesn't exist:
```python
if not os.path.exists(self.log_dir):
    os.makedirs(self.log_dir)
```
Will send in shortly

**Comment by palewire** [comment]
I think that patch is in the latest trunk. [Right hurr](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/management/commands/cleancalaccessrawfile.py#L133) Maybe a git pull will fix it?

**Comment by aboutaaron** [comment]
You right. WE're good to go
