### ISSUE TITLE
issue with building, just my issue?

### ISSUE THREAD

**Issue by rkiddy** [california-civic-data-coalition/django-calaccess-raw-data#261]
I am sorry but I cannot read this error. I had some edits to one of the commands, but I backed them out and did a pull to get the latest. And I still see the error below. Any suggestions on how to read this trace would be appreciated.
```
$         pip install --user dist/django-calaccess-raw-data-0.1.2.tar.gz
Unpacking ./dist/django-calaccess-raw-data-0.1.2.tar.gz
  Running setup.py (path:/tmp/pip-cLOLI4-build/setup.py) egg_info for package from file:///home/ray/Projects/OpenCA/django-calaccess-raw-data/dist/django-calaccess-raw-data-0.1.2.tar.gz
    
Requirement already satisfied (use --upgrade to upgrade): django>=1.7 in /usr/local/lib/python2.7/dist-packages (from django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): csvkit in /usr/local/lib/python2.7/dist-packages (from django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python2.7/dist-packages (from django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): clint in /usr/local/lib/python2.7/dist-packages (from django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): hurry.filesize in /usr/local/lib/python2.7/dist-packages (from django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): xlrd>=0.7.1 in /usr/local/lib/python2.7/dist-packages (from csvkit->django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy>=0.6.6 in /usr/local/lib/python2.7/dist-packages (from csvkit->django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): openpyxl>=2.0.3 in /usr/local/lib/python2.7/dist-packages (from csvkit->django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): six>=1.6.1 in /usr/local/lib/python2.7/dist-packages (from csvkit->django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): dbf==0.94.003 in /usr/local/lib/python2.7/dist-packages (from csvkit->django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): args in /usr/local/lib/python2.7/dist-packages (from clint->django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from hurry.filesize->django-calaccess-raw-data==0.1.2)
Requirement already satisfied (use --upgrade to upgrade): jdcal in /usr/local/lib/python2.7/dist-packages (from openpyxl>=2.0.3->csvkit->django-calaccess-raw-data==0.1.2)
Installing collected packages: django-calaccess-raw-data
  Running setup.py install for django-calaccess-raw-data
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-cLOLI4-build/setup.py", line 31, in <module>
        'hurry.filesize'
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 42, in run
        self.build_packages()
      File "/usr/lib/python2.7/distutils/command/build_py.py", line 373, in build_packages
        self.build_module(module, module_file, package)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 60, in build_module
        outfile, copied = _build_py.build_module(self, module, module_file, package)
      File "/usr/lib/python2.7/distutils/command/build_py.py", line 334, in build_module
        "'package' must be a string (dot-separated), list, or tuple")
    TypeError: 'package' must be a string (dot-separated), list, or tuple
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-cLOLI4-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-D5mKHs-record/install-record.txt --single-version-externally-managed --compile --user:
    running install

running build

running build_py

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-cLOLI4-build/setup.py", line 31, in <module>

    'hurry.filesize'

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run

    return _install.run(self)

  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run

    self.run_command('build')

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 42, in run

    self.build_packages()

  File "/usr/lib/python2.7/distutils/command/build_py.py", line 373, in build_packages

    self.build_module(module, module_file, package)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 60, in build_module

    outfile, copied = _build_py.build_module(self, module, module_file, package)

  File "/usr/lib/python2.7/distutils/command/build_py.py", line 334, in build_module

    "'package' must be a string (dot-separated), list, or tuple")

TypeError: 'package' must be a string (dot-separated), list, or tuple

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-cLOLI4-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-D5mKHs-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-cLOLI4-build
Storing debug log for failure in /home/ray/.pip/pip.log
```

**Comment by rkiddy** [comment]
I searched for this and found some comments about distutils. Based on some of this, I commented out this line at the top of setup.py:
```
from __future__ import unicode_literals
```
This is not the right solution to the problem, is it? Well, it gets me where I need to go for now, so....

**Comment by palewire** [comment]
Hmm. I haven't seen this error before. Very strange looking. 

One thing I do know is that distutils can be a real pain, it might be that you got an older or weird version of it installed. It never hurts trying to upgrade it.

**Comment by rkiddy** [comment]
See http://stackoverflow.com/questions/6625782/unicode-literals-that-work-in-python-3-and-2. Do you think something should be done in this code? Note that it is being suggested that the problem with the literals goes away with python 3.3.

It is expected that you all want to support 3.2 specifically for some time?

**Comment by palewire** [comment]
3.2 isn't all that important to me. So few people have upgraded to 3 that I believe we only need to support it's most recent release.
