### ISSUE TITLE
crash from starting with empty database

### ISSUE THREAD

**Issue by rkiddy** [california-civic-data-coalition/django-calaccess-raw-data#271]
This is worrying. I cleaned up my python environment and am loading a new copy of the ca data into a fresh and empty database and this happened:
```
Loading data files
 Loading CvrSoCd
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/calaccess_raw/management/commands/downloadcalaccessrawdata.py", line 121, in handle
    self.load()
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/calaccess_raw/management/commands/downloadcalaccessrawdata.py", line 251, in load
    call_command("loadcalaccessrawfile", model.__name__)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 22, in handle_label
    self.load(label)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 36, in load
    self.load_mysql(model, csv_path)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 54, in load_mysql
    self.cursor.execute('TRUNCATE TABLE %s' % model._meta.db_table)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/ray/Projects/OpenCA/ccdcEnv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'calaccess_raw.CVR_SO_CD' doesn't exist")
```
If the table does not exist, it obviously does not need to be emptied. I hope this was not something I introduced. :-(

**Comment by rkiddy** [comment]
I then created the tables myself and got this:
```
$ python manage.py downloadcalaccessrawdata --skip-download --skip-unzip --skip-prep --skip-clear --skip-clean
Loading data files
 Loading CvrSoCd
  Table Record count doesn't match CSV. Table: 1	CSV: 13959
 Loading Cvr2SoCd
  Table Record count doesn't match CSV. Table: 1	CSV: 34739
 Loading CvrCampaignDisclosureCd
  Table Record count doesn't match CSV. Table: 1	CSV: 332697
 Loading Cvr2CampaignDisclosureCd
  Table Record count doesn't match CSV. Table: 1	CSV: 93646
 Loading RcptCd
  Table Record count doesn't match CSV. Table: 1	CSV: 8817934
 Loading Cvr3VerificationInfoCd
  Table Record count doesn't match CSV. Table: 1	CSV: 212737
 Loading LoanCd
  Table Record count doesn't match CSV. Table: 1	CSV: 66298
 Loading S401Cd
  Table Record count doesn't match CSV. Table: 1	CSV: 40845
 ```

A single row in each table? Not helpful....

**Comment by rkiddy** [comment]
I have re-created my "ccdc" project, the django project I created that uses the raw-data and browser project. We will see if that helps.

**Comment by rkiddy** [comment]
Interesting. Well, my newly created project did not have the error from the truncate command, but it did get only 1 row per table. I think I can manually load each csv file. We will see.

**Comment by rkiddy** [comment]
Not sure what my issue was here. Cleaned things up and am getting past this.
