### ISSUE TITLE
Tox still used?

### ISSUE THREAD

**Issue by adborden** [california-civic-data-coalition/django-calaccess-raw-data#275]
Wondering how to run the same tests on travis, locally. Running 5 commands separately is cumbersome. Looks like at one point you were using tox, but I get an error when using it, even after [fixing this typo](https://gist.github.com/adborden/38ed621294a5bc36af01).

```
py34 runtests: commands[3] | python example/manage.py test createcalaccessrawmodeldocs
Traceback (most recent call last):
  File "example/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/adborden/projects/brigade/django-calaccess-raw-data/.tox/py34/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/adborden/projects/brigade/django-calaccess-raw-data/.tox/py34/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/adborden/projects/brigade/django-calaccess-raw-data/.tox/py34/lib/python3.4/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/adborden/projects/brigade/django-calaccess-raw-data/.tox/py34/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/adborden/projects/brigade/django-calaccess-raw-data/.tox/py34/lib/python3.4/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/home/adborden/projects/brigade/django-calaccess-raw-data/.tox/py34/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/adborden/projects/brigade/django-calaccess-raw-data/.tox/py34/lib/python3.4/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/adborden/projects/brigade/django-calaccess-raw-data/.tox/py34/lib/python3.4/site-packages/django/test/runner.py", line 209, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/home/adborden/projects/brigade/django-calaccess-raw-data/.tox/py34/lib/python3.4/site-packages/django/test/runner.py", line 121, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "/usr/lib64/python3.4/unittest/loader.py", line 105, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named 'createcalaccessrawmodeldocs'
ERROR: InvocationError: '/home/adborden/projects/brigade/django-calaccess-raw-data/.tox/py34/bin/python example/manage.py test createcalaccessrawmodeldocs'
__________________________________________________________________________________________ summary ___________________________________________________________________________________________
ERROR:   py34: commands failed
```

Is it supported?

**Comment by palewire** [comment]
Thanks for the note. You're right. The tox configuration is out of date. Apologies. I tried to make some improvements. Let me know if it works for you now.

**Comment by adborden** [comment]
Awesome, working now, thanks!

**Comment by palewire** [comment]
Great. Sorry for the inconvenience. If you're out there using the app I'd love any other feedback you.
